### ISSUE TITLE
Class Diagram : class Volunteer fill

### ISSUE THREAD

**Issue by vladuhalys** [vladuhalys/Volunteer_App#5]

**Comment by fzyier** [comment]
Added dynamic fields full_name_, id_ and phone_number_.
Added constructors: default, copy, move, destructor and counstructor with parameters full_name, id and phone_number.
Added setters and getters to the fields.

**Comment by fzyier** [comment]
Added dynamic fields full_name_, id_ and phone_number_.
Added constructors: default, copy, move, destructor and counstructor with parameters full_name, id and phone_number.
Added setters and getters to the fields.
